name: Life Goals API tests
defaults:
  run:
    working-directory: api
on: [push, pull_request]
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test API
        run: |
          yarn install
          yarn test
